server:
  port: 6969
  servlet:
    context-path: /rpc-server

spring:
  application:
    name: rpc-server
  aop:
    proxy-target-class: true

logging:
  level:
    root: debug

alarpc:
  registry:
    ip: 192.168.33.133
  threadpool:
    coreSize: 10
    maxSize: 60
