server:
  port: 6969
  servlet:
    context-path: /rpc-server

spring:
  application:
    name: rpc-server
  aop:
    proxy-target-class: true

logging:
  level:
    root: info

alarpc:
  registry:
    ip: 192.168.33.133

ip: 192.168.33.133


