server:
  port: 6868

spring:
  application:
    name: rpc-client
  cache:
    type: ehcache
    ehcache:
      config: classpath:/config/ehcache.xml

logging:
  level:
    root: info

alarpc:
  registry:
    ip: 192.168.33.133
